# Generated by Django 3.1.1 on 2020-10-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='value',
            new_name='last_value',
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='', max_length=96),
            preserve_default=False,
        ),
    ]
