# Generated by Django 3.1.1 on 2020-10-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20201013_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='users',
            new_name='stocks',
        ),
    ]
