# Generated by Django 3.1.1 on 2020-10-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201013_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['ticker']},
        ),
    ]
