# Generated by Django 3.1.1 on 2020-10-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20201013_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stocks',
            new_name='users',
        ),
    ]
