# Generated by Django 3.1.1 on 2020-10-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20201013_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='primary_exchange',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week52High',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week52Low',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
