# Generated by Django 3.1.1 on 2020-10-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20201015_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ytd_change',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
