# Generated by Django 3.1.1 on 2020-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stock_ytd_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='logo',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
